# Generated by Django 4.2.7 on 2024-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50, null=True)),
                ('FullName', models.CharField(max_length=50)),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
