# Generated by Django 5.0.1 on 2024-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='CompanyName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='Customer_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='FullName',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='PhoneNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
