# Generated by Django 4.2.7 on 2024-01-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JsWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='PhoneNumber',
            field=models.IntegerField(),
        ),
    ]
