# Generated by Django 5.0.1 on 2024-01-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JsWeb', '0003_remove_contact_id_contact_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
